theme: jekyll-theme-cayman

title: "Somnath Purkayastha"
description: "Cloud • Data • AI/ML • Program Leadership"

nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Blog"
    link: "/blog"
  - name: "Contact"
    link: "/contact"

---

© 2026 Somnath Purkayastha
